version: '3.8'

services:
  srgan_service:
    build: .
    container_name: srgan_service
    environment:
      - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN}
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models  # Для сохраненных моделей
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  # Если есть GPU
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3 